import type { MappingType } from "~/types/mapping";

const gender: MappingType = { Male: 1, Female: 0, Other: 2 };

const education: MappingType = {
  "Bachelor's": 0,
  "Master's": 2,
  PhD: 3,
  "High School": 1,
};

const role: MappingType = {
  "Software Engineer": 175,
  "Data Analyst": 18,
  "Senior Manager": 144,
  "Sales Associate": 115,
  Director: 25,
  "Marketing Analyst": 93,
  "Product Manager": 106,
  "Sales Manager": 118,
  "Marketing Coordinator": 94,
  "Senior Scientist": 165,
  "Software Developer": 174,
  "HR Manager": 47,
  "Financial Analyst": 40,
  "Project Manager": 109,
  "Customer Service Rep": 14,
  "Operations Manager": 102,
  "Marketing Manager": 96,
  "Senior Engineer": 130,
  "Data Entry Clerk": 19,
  "Sales Director": 116,
  "Business Analyst": 4,
  "VP of Operations": 189,
  "IT Support": 53,
  Recruiter: 112,
  "Financial Manager": 41,
  "Social Media Specialist": 173,
  "Software Manager": 177,
  "Junior Developer": 66,
  "Senior Consultant": 126,
  "Product Designer": 105,
  CEO: 7,
  Accountant: 1,
  "Data Scientist": 20,
  "Marketing Specialist": 97,
  "Technical Writer": 184,
  "HR Generalist": 46,
  "Project Engineer": 108,
  "Customer Success Rep": 17,
  "Sales Executive": 117,
  "UX Designer": 186,
  "Operations Director": 101,
  "Network Engineer": 98,
  "Administrative Assistant": 2,
  "Strategy Consultant": 179,
  Copywriter: 11,
  "Account Manager": 0,
  "Director of Marketing": 33,
  "Help Desk Analyst": 48,
  "Customer Service Manager": 13,
  "Business Intelligence Analyst": 6,
  "Event Coordinator": 38,
  "VP of Finance": 188,
  "Graphic Designer": 45,
  "UX Researcher": 187,
  "Social Media Manager": 172,
  "Director of Operations": 34,
  "Senior Data Scientist": 129,
  "Junior Accountant": 56,
  "Digital Marketing Manager": 23,
  "IT Manager": 52,
  "Customer Service Representative": 15,
  "Business Development Manager": 5,
  "Senior Financial Analyst": 132,
  "Web Developer": 190,
  "Research Director": 113,
  "Technical Support Specialist": 183,
  "Creative Director": 12,
  "Senior Software Engineer": 168,
  "Human Resources Director": 50,
  "Content Marketing Manager": 10,
  "Technical Recruiter": 182,
  "Sales Representative": 120,
  "Chief Technology Officer": 9,
  "Junior Designer": 65,
  "Financial Advisor": 39,
  "Junior Account Manager": 55,
  "Senior Project Manager": 159,
  "Principal Scientist": 104,
  "Supply Chain Manager": 181,
  "Senior Marketing Manager": 148,
  "Training Specialist": 185,
  "Research Scientist": 114,
  "Junior Software Developer": 86,
  "Public Relations Manager": 110,
  "Operations Analyst": 100,
  "Product Marketing Manager": 107,
  "Senior HR Manager": 136,
  "Junior Web Developer": 90,
  "Senior Project Coordinator": 157,
  "Chief Data Officer": 8,
  "Digital Content Producer": 22,
  "IT Support Specialist": 54,
  "Senior Marketing Analyst": 145,
  "Customer Success Manager": 16,
  "Senior Graphic Designer": 134,
  "Software Project Manager": 178,
  "Supply Chain Analyst": 180,
  "Senior Business Analyst": 124,
  "Junior Marketing Analyst": 71,
  "Office Manager": 99,
  "Principal Engineer": 103,
  "Junior HR Generalist": 70,
  "Senior Product Manager": 155,
  "Junior Operations Analyst": 75,
  "Senior HR Generalist": 135,
  "Sales Operations Manager": 119,
  "Senior Software Developer": 167,
  "Junior Web Designer": 89,
  "Senior Training Specialist": 169,
  "Senior Research Scientist": 161,
  "Junior Sales Representative": 83,
  "Junior Marketing Manager": 73,
  "Junior Data Analyst": 63,
  "Senior Product Marketing Manager": 156,
  "Junior Business Analyst": 58,
  "Senior Sales Manager": 163,
  "Junior Marketing Specialist": 74,
  "Junior Project Manager": 79,
  "Senior Accountant": 123,
  "Director of Sales": 36,
  "Junior Recruiter": 80,
  "Senior Business Development Manager": 125,
  "Senior Product Designer": 153,
  "Junior Customer Support Specialist": 62,
  "Senior IT Support Specialist": 143,
  "Junior Financial Analyst": 68,
  "Senior Operations Manager": 152,
  "Director of Human Resources": 32,
  "Junior Software Engineer": 87,
  "Senior Sales Representative": 164,
  "Director of Product Management": 35,
  "Junior Copywriter": 61,
  "Senior Marketing Coordinator": 146,
  "Senior Human Resources Manager": 139,
  "Junior Business Development Associate": 59,
  "Senior Account Manager": 122,
  "Senior Researcher": 162,
  "Junior HR Coordinator": 69,
  "Director of Finance": 29,
  "Junior Marketing Coordinator": 72,
  "Junior Data Scientist": 64,
  "Senior Operations Analyst": 150,
  "Senior Human Resources Coordinator": 138,
  "Senior UX Designer": 170,
  "Junior Product Manager": 78,
  "Senior Marketing Specialist": 149,
  "Senior IT Project Manager": 142,
  "Senior Quality Assurance Analyst": 160,
  "Director of Sales and Marketing": 37,
  "Senior Account Executive": 121,
  "Director of Business Development": 26,
  "Junior Social Media Manager": 84,
  "Senior Human Resources Specialist": 140,
  "Senior Data Analyst": 127,
  "Director of Human Capital": 31,
  "Junior Advertising Coordinator": 57,
  "Junior UX Designer": 88,
  "Senior Marketing Director": 147,
  "Senior IT Consultant": 141,
  "Senior Financial Advisor": 131,
  "Junior Business Operations Analyst": 60,
  "Junior Social Media Specialist": 85,
  "Senior Product Development Manager": 154,
  "Junior Operations Manager": 77,
  "Senior Software Architect": 166,
  "Junior Research Scientist": 81,
  "Senior Financial Manager": 133,
  "Senior HR Specialist": 137,
  "Senior Data Engineer": 128,
  "Junior Operations Coordinator": 76,
  "Director of HR": 30,
  "Senior Operations Coordinator": 151,
  "Junior Financial Advisor": 67,
  "Director of Engineering": 28,
  "Software Engineer Manager": 176,
  "Back end Developer": 3,
  "Senior Project Engineer": 158,
  "Full Stack Engineer": 44,
  "Front end Developer": 43,
  "Front End Developer": 42,
  "Director of Data Science": 27,
  "Human Resources Coordinator": 49,
  "Junior Sales Associate": 82,
  "Human Resources Manager": 51,
  "Juniour HR Generalist": 92,
  "Juniour HR Coordinator": 91,
  "Digital Marketing Specialist": 24,
  Receptionist: 111,
  "Marketing Director": 95,
  "Social Media Man": 171,
  "Delivery Driver": 21,
};

const country: MappingType = {
  UK: 3,
  USA: 4,
  Canada: 1,
  China: 2,
  Australia: 0,
};

const race: MappingType = {
  White: 9,
  Hispanic: 5,
  Asian: 1,
  Korean: 6,
  Chinese: 4,
  Australian: 2,
  Welsh: 8,
  "African American": 0,
  Mixed: 7,
  Black: 3,
};

export const Mapping = {
  country: country,
  race: race,
  role: role,
  education: education,
  gender: gender,
};
